
services:
  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=${PORT:-8000}
      - PYTHONUNBUFFERED=1
    ports:
      - "${PORT:-8000}:8000"
    develop:
      watch:
        - path: ./backend/requirements.txt
          action: rebuild
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      # prestart:
        # condition: service_completed_successfully
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    # restart: unless-stopped
    command:
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


 

volumes:
  postgres_data: