"""Delete title 2 from chat model

Revision ID: 2a0b68507cc9
Revises: 69ba38f24fbb
Create Date: 2025-09-29 17:23:00.988680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0b68507cc9'
down_revision: Union[str, Sequence[str], None] = '69ba38f24fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'title2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
