"""Change chat model

Revision ID: 7fff44bad2aa
Revises: 2a0b68507cc9
Create Date: 2025-10-03 12:26:40.558098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fff44bad2aa'
down_revision: Union[str, Sequence[str], None] = '2a0b68507cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('description', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('type', sa.Enum('dm', 'grup', name='chat_type_enum', native_enum=False), nullable=False))
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('chats', 'type')
    op.drop_column('chats', 'description')
    # ### end Alembic commands ###
